name: nf-core Docker push
# This builds the docker image and pushes it to DockerHub
# Runs on nf-core repo releases and push event to 'dev' branch (PR merges)
on:
  push:
    branches:
      - dev
  release:
    types: [published]

push_dockerhub:
  name: Push new Docker image to Docker Hub
  runs-on: ubuntu-latest
  # Only run for the nf-core repo, for releases and merged PRs
  if: ${{ github.repository == 'nf-core/deepvariant' }}
  env:
    DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  steps:
    - name: Check out pipeline code
      uses: actions/checkout@v2

    - name: Build new docker image
      run: docker build --no-cache . -t nfcore/deepvariant:latest

    - name: Push Docker image to DockerHub (dev)
      if: ${{ github.event_name == 'push' }}
      run: |
        echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker tag nfcore/deepvariant:latest nfcore/deepvariant:dev
        docker push nfcore/deepvariant:dev

    - name: Push Docker image to DockerHub (release)
      if: ${{ github.event_name == 'release' }}
      run: |
        echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker push nfcore/deepvariant:latest
        docker tag nfcore/deepvariant:latest nfcore/deepvariant:${{ github.event.release.tag_name }}
        docker push nfcore/deepvariant:${{ github.event.release.tag_name }}
